ProyWebStore/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using ProyWebStore.DAO;
using ProyWebStore.Models;
using System.Text;

namespace ProyWebStore.Controllers
{
    [Authorize(Roles = "1,2")]
    public class ClienteController : Controller
    {
        List<Cliente> listaClientes = new List<Cliente>();

        public async Task<List<Cliente>> traerClientes()
        {
            using (HttpClient cliente = new HttpClient())
            {
                var respuesta = await cliente.GetAsync("http://localhost:5169/api/ClienteAPI/GetClientes");
                string cadena = await respuesta.Content.ReadAsStringAsync();
                return JsonConvert.DeserializeObject<List<Cliente>>(cadena)!;
            }
        }
        public async Task<ActionResult> IndexClientes()
        {
            listaClientes = await traerClientes();
            return View(listaClientes);
        }

        public async Task<ActionResult> DetailsClientes(int id)
        {
            listaClientes = await traerClientes();
            Cliente buscado = listaClientes.Find(c => c.idCliente == id)!;
            return View(buscado);
        }

        public async Task<string> enviarCliente(int opcion, Cliente objcli)
        {
            string resultado = string.Empty;
            using (var httpcliente = new HttpClient())
            {
                var contenido = new StringContent(JsonConvert.SerializeObject(objcli), Encoding.UTF8, "application/json");

                HttpResponseMessage respuesta = new HttpResponseMessage();

                if (opcion == 1) // Post = Grabar
                    respuesta = await httpcliente.PostAsync("http://localhost:5169/api/ClienteAPI/PostClientes", contenido);
                else // Put = Actualizar
                    respuesta = await httpcliente.PutAsync("http://localhost:5169/api/ClienteAPI/PutClientes", contenido);

                resultado = await respuesta.Content.ReadAsStringAsync();
            }
            return resultado;
        }

        public ActionResult CreateCliente()
        {
            return View();
        }

        // POST: CategoriaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateCliente(Cliente obj)
        {
            if (ModelState.IsValid)
            {
                TempData["mensaje"] = await enviarCliente(1, obj);
                return RedirectToAction("IndexClientes");
            }
            ViewBag.mensaje = "Error al Grabar el Cliente";
            return View(obj);
        }

        public async Task<ActionResult> EditClientes(int id)
        {
            listaClientes = await traerClientes();
            Cliente buscado = listaClientes.Find(c => c.idCliente == id)!;
            return View(buscado);
        }

        // POST: ClienteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditClientes(int id, Cliente obj)
        {
            if (ModelState.IsValid == true)
            {
                TempData["mensaje"] = await enviarCliente(2, obj);
                return RedirectToAction("IndexClientes");
            }
            ViewBag.mensaje = "Error al Actualizar el Cliente";
            return View(obj);
        }

        // GET: ClienteController/Delete/5
        public async Task<ActionResult> DeleteClientes(int id)
        {
            listaClientes = await traerClientes();
            Cliente buscado = listaClientes.Find(c => c.idCliente == id)!;
            return View(buscado);
        }

        // POST: ClienteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteClientes(int id, IFormCollection collection)
        { 
            using (var httpcliente = new HttpClient())
            {
                var respuesta = await httpcliente.DeleteAsync("http://localhost:5169/api/ClienteAPI/DeleteClientes/" + id);
                string respuestaAPI = await respuesta.Content.ReadAsStringAsync();
                TempData["mensaje"] = respuestaAPI;
            }
            return RedirectToAction("IndexClientes");
        }

    }

}

ProyWebStore/Controllers/MarcaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProyWebStore.DAO;
using ProyWebStore.Models;
using System.Data.SqlClient;

namespace ProyWebStore.Controllers
{
    [Authorize(Roles = "1")]
    public class MarcaController : Controller
    {
        private readonly MarcaDAO marcaDAO;

        public MarcaController(MarcaDAO marca)
        {
            marcaDAO = marca;
        }

        public IActionResult IndexMarcas()
        {
            var listado = marcaDAO.GetMarcas();
            return View(listado);
        }

        public ActionResult CreateMarca()
        {
            Marca nueva = new Marca();
            return View(nueva);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateMarca(Marca obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["mensaje"] = marcaDAO.GrabarMarca(obj);
                    return RedirectToAction(nameof(IndexMarcas));
                }
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = "Error: " + ex.Message;
            }
            return View(obj);
        }

        public ActionResult EditMarca(int id)
        {
            var buscada = marcaDAO.GetMarcas().Find(marca => marca.IdMarca == id);
            return View(buscada);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditMarca(int id, Marca obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["mensaje"] = marcaDAO.GrabarMarca(obj);
                    return RedirectToAction(nameof(IndexMarcas));
                }
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = "Error: " + ex.Message;
            }
            return View(obj);
        }

        public ActionResult DeleteMarca(int id)
        {
            var buscada = marcaDAO.GetMarcas().Find(marca => marca.IdMarca == id);
            return View(buscada);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteMarca(int id, IFormCollection collection)
        {
            try
            {
                TempData["mensaje"] = marcaDAO.EliminarMarca(id);
                return RedirectToAction(nameof(IndexMarcas));
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = "Error: " + ex.Message;
            }
            return View();
        }
        
    }
}

ProyWebStore/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyWebStore.DAO;
using ProyWebStore.Models;
using System.Data.SqlClient;

namespace ProyWebStore.Controllers
{
    [Authorize(Roles = "1")]
    public class ProductoController : Controller
    {
        private readonly ProductoDAO productoDAO;
        private readonly MarcaDAO marcaDAO;
        private readonly CategoriaDAO categoriaDAO;
        private readonly IWebHostEnvironment _env;

        public ProductoController(ProductoDAO producto, MarcaDAO marca, CategoriaDAO categoria, IWebHostEnvironment env)
        {
            productoDAO = producto;
            marcaDAO = marca;
            categoriaDAO = categoria;
            _env = env;
        }

        public ActionResult IndexProductos()
        {
            var listado = productoDAO.GetProductos();
            return View(listado);
        }
        public ActionResult DetailsProducto(int id)
        {
            var buscado = productoDAO.GetProductos().Find(art => art.IdProducto == id);
            return View(buscado);
        }

        public ActionResult CreateProducto()
        {
            Producto nuevo = new Producto();
            ViewBag.categoria = new SelectList(categoriaDAO.GetCategoriasActivas(), "IdCategoria", "Descripcion");
            ViewBag.marca = new SelectList(marcaDAO.GetMarcasActivas(), "IdMarca", "Descripcion");
            return View(nuevo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProducto(Producto obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["mensaje"] = productoDAO.GrabarProducto(obj);
                    return RedirectToAction(nameof(IndexProductos));
                }
            }
            catch (Exception ex)
            {
                ViewBag.error = "Error: " + ex.Message;
            }
            
            ViewBag.categoria = new SelectList(categoriaDAO.GetCategoriasActivas(), "IdCategoria", "Descripcion", obj.IdCategoria);
            ViewBag.marca = new SelectList(marcaDAO.GetMarcasActivas(), "IdMarca", "Descripcion", obj.IdMarca);
            return View(obj);
        }
        
        public ActionResult EditProducto(int id)
        {
            var buscado = productoDAO.GetProductos().Find(p => p.IdProducto == id);
            ViewBag.categoria = new SelectList(categoriaDAO.GetCategoriasActivas(), "IdCategoria", "Descripcion");
            ViewBag.marca = new SelectList(marcaDAO.GetMarcasActivas(), "IdMarca", "Descripcion");
            return View(buscado);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProducto(int id, Producto obj)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        TempData["mensaje"] = productoDAO.GrabarProducto(obj);
                        return RedirectToAction(nameof(IndexProductos));
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.error = "Error: " + ex.Message;
                }
            }
            ViewBag.categoria = new SelectList(categoriaDAO.GetCategoriasActivas(), "IdCategoria", "Descripcion", obj.IdCategoria);
            ViewBag.marca = new SelectList(marcaDAO.GetMarcasActivas(), "IdMarca", "Descripcion", obj.IdMarca);
            return View(obj);
        }

        public ActionResult DeleteProducto(int id)
        {
            var buscado = productoDAO.GetProductos().Find(p => p.IdProducto == id);
            return View(buscado);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteProducto(int id, IFormCollection collection)
        {
            try
            {
                TempData["mensaje"] = productoDAO.EliminarProducto(id);
                return RedirectToAction(nameof(IndexProductos));
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = "Error: " + ex.Message;
            }
            return View();
        } 
    }
}

ProyWebStore/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NuGet.Protocol.Plugins;
using ProyWebStore.DAO;
using ProyWebStore.Models;
using System.Data.SqlClient;
using System.Numerics;
using System.Security.Claims;

namespace ProyWebStore.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly UsuarioDAO usuarioDAO;
        private readonly RolesDAO rolesDAO;
        public UsuarioController(UsuarioDAO usuario, RolesDAO roles)
        {
            usuarioDAO = usuario;
            rolesDAO = roles;
        }

        // GET: UsuarioController
        public ActionResult IndexUsuarios()
        {
            var listado = usuarioDAO.GetUsuarios();
            return View(listado);
        }

        // GET: UsuarioController/Details/5
        public ActionResult DetailsUsuario(int id)
        {
            var buscado = usuarioDAO.GetUsuarios().Find( u => u.IdUsuario == id);
            return View(buscado);
        }

        // GET: UsuarioController/Create
        public ActionResult CreateUsuario()
        {
            Usuario nuevo = new Usuario();
            ViewBag.ROL = new SelectList(rolesDAO.GetRoles(), "IdRol", "Nombre");
            return View(nuevo);
        }

        // POST: UsuarioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUsuario(Usuario obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["mensaje"] = usuarioDAO.GrabarUsuario(obj);
                    return RedirectToAction(nameof(IndexUsuarios));
                }
            }
            catch(Exception ex)
            {
                ViewBag.mensaje = "Error : " + ex.Message;
            }
            ViewBag.ROL = new SelectList(rolesDAO.GetRoles(), "IdRol", "Nombre");
            return View(obj);
        }

        // GET: UsuarioController/Edit/5
        public ActionResult EditUsuario(int id)
        {
            var buscado = usuarioDAO.GetUsuarios().Find(u => u.IdUsuario == id);
            ViewBag.ROL = new SelectList(rolesDAO.GetRoles(), "IdRol", "Nombre");
            return View(buscado);
        }

        // POST: UsuarioController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUsuario(int id, Usuario obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["mensaje"] = usuarioDAO.GrabarUsuario(obj);
                    return RedirectToAction(nameof(IndexUsuarios));
                }
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = "Error : " + ex.Message;
            }
            ViewBag.ROL = new SelectList(rolesDAO.GetRoles(), "IdRol", "Nombre");
            return View(obj);
        }

        // GET: UsuarioController/Delete/5
        public ActionResult DeleteUsuario(int id)
        {
            var buscado = usuarioDAO.GetUsuarios().Find(u => u.IdUsuario == id);
            return View(buscado);
        }

        // POST: UsuarioController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteUsuario(int id, IFormCollection collection)
        {
            try
            {
                TempData["mensaje"] = usuarioDAO.EliminarUsuario(id);
                return RedirectToAction(nameof(IndexUsuarios));
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = "Error: " + ex.Message;
            }
            return View();
        } 
    }
}

ProyWebStore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ELECTRO-STOCK</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyWebStore.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar px-5 navbar-expand-sm text-white navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand text-white fw-bold" asp-area="" asp-controller="Home" asp-action="Index">ELECTRO-STOCK</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        @if (User.IsInRole("1"))
                        {
                            <li class="nav-item">
                                <a class=" nav-link text-white d-flex align-items-center gap-1" asp-area="" asp-controller="Categoria" asp-action="IndexCategorias">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-category"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 4h6v6h-6z" /><path d="M14 4h6v6h-6z" /><path d="M4 14h6v6h-6z" /><path d="M17 17m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" /></svg>
                                    Categorias
                                </a>
                            </li>
                        }
                        @if (User.IsInRole("1"))
                        {
                            <li class="nav-item">
                                <a class=" nav-link text-white d-flex align-items-center gap-1" asp-area="" asp-controller="Marca" asp-action="IndexMarcas">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-brand-medium"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 4m0 2a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2z" /><path d="M8 9h1l3 3l3 -3h1" /><path d="M8 15l2 0" /><path d="M14 15l2 0" /><path d="M9 9l0 6" /><path d="M15 9l0 6" /></svg>
                                    Marcas
                                </a>
                            </li>
                        }
                        @if (User.IsInRole("1"))
                        {
                            <li class="nav-item">
                                <a class=" nav-link text-white d-flex align-items-center gap-1" asp-area="" asp-controller="Producto" asp-action="IndexProductos">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-basket"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M10 14a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" /><path d="M5.001 8h13.999a2 2 0 0 1 1.977 2.304l-1.255 7.152a3 3 0 0 1 -2.966 2.544h-9.512a3 3 0 0 1 -2.965 -2.544l-1.255 -7.152a2 2 0 0 1 1.977 -2.304z" /><path d="M17 10l-2 -6" /><path d="M7 10l2 -6" /></svg>
                                    Productos
                                </a>
                            </li>

                        }
                        @if (User.IsInRole("1"))
                        {
                            <li class="nav-item">
                                <a class=" nav-link text-white d-flex align-items-center gap-1" asp-area="" asp-controller="Usuario" asp-action="IndexUsuarios">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-user-cog"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0" /><path d="M6 21v-2a4 4 0 0 1 4 -4h2.5" /><path d="M19.001 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" /><path d="M19.001 15.5v1.5" /><path d="M19.001 21v1.5" /><path d="M22.032 17.25l-1.299 .75" /><path d="M17.27 20l-1.3 .75" /><path d="M15.97 17.25l1.3 .75" /><path d="M20.733 20l1.3 .75" /></svg>
                                    Usuarios
                                </a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class=" nav-link text-white d-flex align-items-center gap-1" asp-area="" asp-controller="Cliente" asp-action="IndexClientes">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-users-group"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M10 13a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" /><path d="M8 21v-1a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v1" /><path d="M15 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" /><path d="M17 10h2a2 2 0 0 1 2 2v1" /><path d="M5 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" /><path d="M3 13v-1a2 2 0 0 1 2 -2h2" /></svg>
                                Clientes
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class=" nav-link text-white d-flex align-items-center gap-1" asp-area="" asp-controller="Carrito" asp-action="ListarProductos">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-building-store"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 21l18 0" /><path d="M3 7v1a3 3 0 0 0 6 0v-1m0 1a3 3 0 0 0 6 0v-1m0 1a3 3 0 0 0 6 0v-1h-18l2 -4h14l2 4" /><path d="M5 21l0 -10.15" /><path d="M19 21l0 -10.15" /><path d="M9 21v-4a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v4" /></svg>
                                Generar Venta
                            </a>
                        </li>
                        
                    </ul>
                </div>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white d-flex align-items-center gap-1" asp-area="" asp-controller="Home" asp-action="Salir">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-logout"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2" /><path d="M9 12h12l-3 -3" /><path d="M18 15l3 -3" /></svg>
                            Cerrar Sesión
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
 
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted px-5">
        <div >
            &copy; 2024 - ELECTRO-STOCK - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>